
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCategoriaPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    publicadores.ObjectFactory.class
})
public interface CCategoriaPublish {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CCategoriaPublish/altaCategoriaRequest", output = "http://publicadores/CCategoriaPublish/altaCategoriaResponse")
    public void altaCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtElementoUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CCategoriaPublish/listarElemCategoriaRequest", output = "http://publicadores/CCategoriaPublish/listarElemCategoriaResponse")
    public DtElementoUsuarioArray listarElemCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtElementoWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CCategoriaPublish/listarVideosPublicosCategoriaRequest", output = "http://publicadores/CCategoriaPublish/listarVideosPublicosCategoriaResponse")
    public DtElementoWebArray listarVideosPublicosCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns publicadores.DtElementoWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CCategoriaPublish/listarListasPublicasCategoriaRequest", output = "http://publicadores/CCategoriaPublish/listarListasPublicasCategoriaResponse")
    public DtElementoWebArray listarListasPublicasCategoria(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CCategoriaPublish/existeCategoriaRequest", output = "http://publicadores/CCategoriaPublish/existeCategoriaResponse")
    public boolean existeCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CCategoriaPublish/listarCategoriasRequest", output = "http://publicadores/CCategoriaPublish/listarCategoriasResponse")
    public StringArray listarCategorias();

}
