
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CListaRepPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    publicadores.ObjectFactory.class
})
public interface CListaRepPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.DtElementoWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/busquedaRequest", output = "http://publicadores/CListaRepPublish/busquedaResponse")
    public DtElementoWebArray busqueda(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarListaDefectoRequest", output = "http://publicadores/CListaRepPublish/agregarListaDefectoResponse")
    public void agregarListaDefecto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarListasDeUsuarioRequest", output = "http://publicadores/CListaRepPublish/listarListasDeUsuarioResponse")
    public StringArray listarListasDeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/existeListaRequest", output = "http://publicadores/CListaRepPublish/existeListaResponse")
    public boolean existeLista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/setuVidRequest", output = "http://publicadores/CListaRepPublish/setuVidResponse")
    public void setuVid(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/setVideoRequest", output = "http://publicadores/CListaRepPublish/setVideoResponse")
    public void setVideo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarListasParticularesPublicasRequest", output = "http://publicadores/CListaRepPublish/listarListasParticularesPublicasResponse")
    public StringArray listarListasParticularesPublicas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarListasPorDefectoRequest", output = "http://publicadores/CListaRepPublish/listarListasPorDefectoResponse")
    public StringArray listarListasPorDefecto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarCategoriaAListaRequest", output = "http://publicadores/CListaRepPublish/agregarCategoriaAListaResponse")
    public void agregarCategoriaALista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarListaParticularRequest", output = "http://publicadores/CListaRepPublish/agregarListaParticularResponse")
    public void agregarListaParticular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarListaParticularCategoriaRequest", output = "http://publicadores/CListaRepPublish/agregarListaParticularCategoriaResponse")
    public void agregarListaParticularCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarVideoListaParticularRequest", output = "http://publicadores/CListaRepPublish/agregarVideoListaParticularResponse")
    public void agregarVideoListaParticular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/agregarVideoListaPorDefectoRequest", output = "http://publicadores/CListaRepPublish/agregarVideoListaPorDefectoResponse")
    public void agregarVideoListaPorDefecto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/eliminarVideoDeListaRequest", output = "http://publicadores/CListaRepPublish/eliminarVideoDeListaResponse")
    public void eliminarVideoDeLista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/existeListaDefectoRequest", output = "http://publicadores/CListaRepPublish/existeListaDefectoResponse")
    public boolean existeListaDefecto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/existeListaParticularRequest", output = "http://publicadores/CListaRepPublish/existeListaParticularResponse")
    public boolean existeListaParticular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarListasParticularesRequest", output = "http://publicadores/CListaRepPublish/listarListasParticularesResponse")
    public StringArray listarListasParticulares(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/modificarCategoriaRequest", output = "http://publicadores/CListaRepPublish/modificarCategoriaResponse")
    public void modificarCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtElementoWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarVideosListaWebRequest", output = "http://publicadores/CListaRepPublish/listarVideosListaWebResponse")
    public DtElementoWebArray listarVideosListaWeb(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/modificarInfoListaRequest", output = "http://publicadores/CListaRepPublish/modificarInfoListaResponse")
    public void modificarInfoLista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/eliminarCategoriaRequest", output = "http://publicadores/CListaRepPublish/eliminarCategoriaResponse")
    public void eliminarCategoria();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/setListaRequest", output = "http://publicadores/CListaRepPublish/setListaResponse")
    public void setLista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CListaRepPublish/setuListRequest", output = "http://publicadores/CListaRepPublish/setuListResponse")
    public void setuList(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtListaRep
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/obtenerListaDeUsuarioRequest", output = "http://publicadores/CListaRepPublish/obtenerListaDeUsuarioResponse")
    public DtListaRep obtenerListaDeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtVideoUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CListaRepPublish/listarVideosdeListaRequest", output = "http://publicadores/CListaRepPublish/listarVideosdeListaResponse")
    public DtVideoUsuarioArray listarVideosdeLista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
