
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CUsuarioPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    publicadores.ObjectFactory.class
})
public interface CUsuarioPublish {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/agregarUsuarioRequest", output = "http://publicadores/CUsuarioPublish/agregarUsuarioResponse")
    public void agregarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DtFecha arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/modificarCatCanalRequest", output = "http://publicadores/CUsuarioPublish/modificarCatCanalResponse")
    public void modificarCatCanal(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/dejarDeSeguirUsuarioRequest", output = "http://publicadores/CUsuarioPublish/dejarDeSeguirUsuarioResponse")
    public void dejarDeSeguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/esCanalPublicoRequest", output = "http://publicadores/CUsuarioPublish/esCanalPublicoResponse")
    public boolean esCanalPublico(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/existeEmailRequest", output = "http://publicadores/CUsuarioPublish/existeEmailResponse")
    public boolean existeEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/existeNicknameRequest", output = "http://publicadores/CUsuarioPublish/existeNicknameResponse")
    public boolean existeNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtUsuarioWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarNickFotoWebRequest", output = "http://publicadores/CUsuarioPublish/listarNickFotoWebResponse")
    public DtUsuarioWebArray listarNickFotoWeb(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarSeguidoresRequest", output = "http://publicadores/CUsuarioPublish/listarSeguidoresResponse")
    public StringArray listarSeguidores();

    /**
     * 
     * @return
     *     returns publicadores.DtCanal
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/obtenerInfoCanalRequest", output = "http://publicadores/CUsuarioPublish/obtenerInfoCanalResponse")
    public DtCanal obtenerInfoCanal();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/obtenerInfoUsuarioRequest", output = "http://publicadores/CUsuarioPublish/obtenerInfoUsuarioResponse")
    public DtUsuario obtenerInfoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/seguirUsuarioRequest", output = "http://publicadores/CUsuarioPublish/seguirUsuarioResponse")
    public void seguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/iniciarSesionRequest", output = "http://publicadores/CUsuarioPublish/iniciarSesionResponse")
    public int iniciarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtUsuarioWeb
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/obtenerUsuarioWebNickRequest", output = "http://publicadores/CUsuarioPublish/obtenerUsuarioWebNickResponse")
    public DtUsuarioWeb obtenerUsuarioWebNick(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtUsuarioWeb
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/obtenerUsuarioWebEmailRequest", output = "http://publicadores/CUsuarioPublish/obtenerUsuarioWebEmailResponse")
    public DtUsuarioWeb obtenerUsuarioWebEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicadores.DtUsuarioWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarUsuariosWebRequest", output = "http://publicadores/CUsuarioPublish/listarUsuariosWebResponse")
    public DtUsuarioWebArray listarUsuariosWeb();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/eliminarUsuarioRequest", output = "http://publicadores/CUsuarioPublish/eliminarUsuarioResponse")
    public void eliminarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/agregarVisitaRequest", output = "http://publicadores/CUsuarioPublish/agregarVisitaResponse")
    public void agregarVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtVisitaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarMasVisitadosRequest", output = "http://publicadores/CUsuarioPublish/listarMasVisitadosResponse")
    public DtVisitaArray listarMasVisitados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/crearTokenRequest", output = "http://publicadores/CUsuarioPublish/crearTokenResponse")
    public void crearToken(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.DtUsuarioWeb
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/obtenerUsuarioConTokenRequest", output = "http://publicadores/CUsuarioPublish/obtenerUsuarioConTokenResponse")
    public DtUsuarioWeb obtenerUsuarioConToken(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.DtCanalWebArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/busquedaRequest", output = "http://publicadores/CUsuarioPublish/busquedaResponse")
    public DtCanalWebArray busqueda(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/agregarCanalRequest", output = "http://publicadores/CUsuarioPublish/agregarCanalResponse")
    public void agregarCanal();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarSeguidosRequest", output = "http://publicadores/CUsuarioPublish/listarSeguidosResponse")
    public StringArray listarSeguidos();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/modificarImagenRequest", output = "http://publicadores/CUsuarioPublish/modificarImagenResponse")
    public void modificarImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/modificarContrasenaRequest", output = "http://publicadores/CUsuarioPublish/modificarContrasenaResponse")
    public void modificarContrasena(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/modificarInfoCanalRequest", output = "http://publicadores/CUsuarioPublish/modificarInfoCanalResponse")
    public void modificarInfoCanal(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        boolean arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/CUsuarioPublish/modificarInfoUsuarioRequest", output = "http://publicadores/CUsuarioPublish/modificarInfoUsuarioResponse")
    public void modificarInfoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DtFecha arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/CUsuarioPublish/listarUsuariosRequest", output = "http://publicadores/CUsuarioPublish/listarUsuariosResponse")
    public StringArray listarUsuarios();

}
