
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CUsuarioPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://127.0.0.1:16000/Usuario?wsdl")
public class CUsuarioPublishService
    extends Service
{

    private final static URL CUSUARIOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSUARIOPUBLISHSERVICE_EXCEPTION;
    private final static QName CUSUARIOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "CUsuarioPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:16000/Usuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSUARIOPUBLISHSERVICE_WSDL_LOCATION = url;
        CUSUARIOPUBLISHSERVICE_EXCEPTION = e;
    }

    public CUsuarioPublishService() {
        super(__getWsdlLocation(), CUSUARIOPUBLISHSERVICE_QNAME);
    }

    public CUsuarioPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSUARIOPUBLISHSERVICE_QNAME, features);
    }

    public CUsuarioPublishService(URL wsdlLocation) {
        super(wsdlLocation, CUSUARIOPUBLISHSERVICE_QNAME);
    }

    public CUsuarioPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSUARIOPUBLISHSERVICE_QNAME, features);
    }

    public CUsuarioPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUsuarioPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CUsuarioPublish
     */
    @WebEndpoint(name = "CUsuarioPublishPort")
    public CUsuarioPublish getCUsuarioPublishPort() {
        return super.getPort(new QName("http://publicadores/", "CUsuarioPublishPort"), CUsuarioPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CUsuarioPublish
     */
    @WebEndpoint(name = "CUsuarioPublishPort")
    public CUsuarioPublish getCUsuarioPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "CUsuarioPublishPort"), CUsuarioPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSUARIOPUBLISHSERVICE_EXCEPTION!= null) {
            throw CUSUARIOPUBLISHSERVICE_EXCEPTION;
        }
        return CUSUARIOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
