
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CVideoPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://127.0.0.1:16000/Video?wsdl")
public class CVideoPublishService
    extends Service
{

    private final static URL CVIDEOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException CVIDEOPUBLISHSERVICE_EXCEPTION;
    private final static QName CVIDEOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "CVideoPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:16000/Video?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CVIDEOPUBLISHSERVICE_WSDL_LOCATION = url;
        CVIDEOPUBLISHSERVICE_EXCEPTION = e;
    }

    public CVideoPublishService() {
        super(__getWsdlLocation(), CVIDEOPUBLISHSERVICE_QNAME);
    }

    public CVideoPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CVIDEOPUBLISHSERVICE_QNAME, features);
    }

    public CVideoPublishService(URL wsdlLocation) {
        super(wsdlLocation, CVIDEOPUBLISHSERVICE_QNAME);
    }

    public CVideoPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CVIDEOPUBLISHSERVICE_QNAME, features);
    }

    public CVideoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CVideoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CVideoPublish
     */
    @WebEndpoint(name = "CVideoPublishPort")
    public CVideoPublish getCVideoPublishPort() {
        return super.getPort(new QName("http://publicadores/", "CVideoPublishPort"), CVideoPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CVideoPublish
     */
    @WebEndpoint(name = "CVideoPublishPort")
    public CVideoPublish getCVideoPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "CVideoPublishPort"), CVideoPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CVIDEOPUBLISHSERVICE_EXCEPTION!= null) {
            throw CVIDEOPUBLISHSERVICE_EXCEPTION;
        }
        return CVIDEOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
